-- Startup commands
hl.on("hyprland.start", function()
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("quickshell -p ~/.config/hypr/scripts/quickshell/Main.qml")
    hl.exec_cmd("quickshell -p ~/.config/hypr/scripts/quickshell/TopBar.qml")
    hl.exec_cmd("quickshell -p ~/.config/hypr/scripts/quickshell/Floating.qml")
    hl.exec_cmd("python3 ~/.config/hypr/scripts/quickshell/focustime/focus_daemon.py &")
    hl.exec_cmd("~/.config/hypr/scripts/init.sh")
    hl.exec_cmd("~/.config/hypr/scripts/settings_watcher.sh &")
    hl.exec_cmd("~/.config/hypr/scripts/qs_manager.sh toggle guide &")
    hl.exec_cmd("playerctld")
    hl.exec_cmd("swayosd-server --top-margin 0.9 --style \"$HOME/.config/swayosd/style.css\"")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("~/.config/hypr/scripts/volume_listener.sh")
    hl.exec_cmd("~/.config/hypr/scripts/update_notifier.sh")
end)
